config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications do 
      resources :comments, only: [:create]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }
  post'/reactions', to: 'reactions#user_reaction', as: 'user_reaction'
  get '/my_reactions', to: 'reactions#publication_with_reactions', as: 'my_reactions'

  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
   get "/publications", to: "publications#index", as: "user_root" 
end

app/models/publication.rb
class Publication < ApplicationRecord
  belongs_to :user
  has_many :reactions, dependent: :destroy
  has_many :users, through: :reactions
  has_many :comments, dependent: :destroy


    def count_with_kind(arg)
      number = self.reactions.where(kind: arg).count
      return "#{arg} - #{number}"
    end

    def find_kind_user_relation(user)
      self.reactions.find_by(user_id: user.id).kind
    end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController
  before_action :set_publication, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  #before_action :authenticate_user! [:index, :show]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    @comments = @publication.comments
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user_id = current_user.id

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:image, :title, :description)
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication, class: "mt-4") do |form| %>
  <% if publication.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :image, class: "form-label" %>
    <%= form.text_field :image, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div>
    <%= form.submit "Save changes", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/publications/_publication.html.erb
<div id="<%= dom_id publication %>">
  <p>
    <%= image_tag publication.image, sixe: "300x300" %>
  </p>

  <p>
    <strong>Title:</strong>
    <%= publication.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= publication.description %>
  </p>

  <p>
    <strong>User:</strong>
    <%= publication.user.email %>
  </p>

</div>

app/views/publications/edit.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Editar Publicación</h1>

  <%= render "form", publication: @publication %>

  <div class="mt-4">
    <%= link_to "Ver esta publicación", @publication, class: "btn btn-secondary mr-2" %>
    <%= link_to "Volver a las publicaciones", publications_path, class: "btn btn-outline-secondary" %>
  </div>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container mt-5">
  <h1 class="mb-4">Publicaciones</h1>

  <div class="row" id="publications">
    <% @publications.each do |publication| %>
      <div class="col-md-6 mb-4">
        <%= render publication %>
        <p class="mt-2">
          <%= link_to "Ver esta publicación", publication, class: "btn btn-secondary" %>
        </p>
      </div>
    <% end %>
  </div>

  <%= link_to "Nueva publicación", new_publication_path, class: "btn btn-primary" %>
</div>

app/views/publications/new.html.erb
<div class="container mt-5">
  <h1 class="mb-4">Nueva publicación</h1>

  <%= render "form", publication: @publication %>

  <div class="mt-4">
    <%= link_to "Back to publications", publications_path, class: "btn btn-secondary" %>
  </div>
</div>

app/views/publications/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="container mt-5">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <div class="alert alert-success" role="alert">
        <%= notice %>
      </div>
      <%= render @publication %>

      <% if user_signed_in? %>
        <% if current_user.id == @publication.user_id %>
          <div class="btn-group" role="group">
            <%= link_to "Editar Publicación", edit_publication_path(@publication), class: "btn btn-primary mr-2" %>
            <%= button_to "Borrar publicación", @publication, method: :delete, class: "btn btn-danger", data: { confirm: "¿Estás seguro?" } %>
          </div>
        <% end %>
      <% end %>
      <h2>Comentarios</h2>
      <% @publication.comments.each do |comment| %>
        <div class="card mb-2">
          <div class="card-body">
            <h5 class="card-title"><%= comment.user.email %></h5>
            <p class="card-text"><%= comment.content %></p>
          </div>
        </div>
      <% end %>
      <% if user_signed_in? %>
        <%= form_with(model: [@publication, Comment.new], class: "mb-4") do |form| %>
          <div class="form-group">
            <%= form.text_area :content, placeholder: "Escribe tu comentario aquí", class: "form-control" %>
          </div>
          <%= form.submit "Comentar", class: "btn btn-primary" %>
        <% end %>
      <% else %>
        <p>Inicia sesión para agregar un comentario.</p>
      <% end %>

      <%= link_to "Volver a las publicaciones", publications_path, class: "btn btn-secondary mt-3" %>
      <div>
        <%= render 'reactions/options' %>
      </div>
    </div>
  </div>
</div>
</div>