config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications do 
      resources :comments, only: [:create]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }
  post'/reactions', to: 'reactions#user_reaction', as: 'user_reaction'
  get '/my_reactions', to: 'reactions#publication_with_reactions', as: 'my_reactions'

  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
   get "/publications", to: "publications#index", as: "user_root" 
end

app/views/componentes/_barra.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Navbar</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Home", homes_index_path, class:"nav-link" %>
          </li>
          <% if user_signed_in? %>
          <a class="nav-link">Hola <%= current_user.name %></a> 
          <li class="nav-item">
            <%= link_to "Publicaciones", publications_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Cerrar Sesion", destroy_user_session_path, class: "nav-link" %>
          </li>
          <%= link_to 'Tus reacciones', my_reactions_path, class: 'nav-link' %>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Registro", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
        
        </ul>
      </div>
    </div>
  </nav>