config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :publications do 
      resources :comments, only: [:create]
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations"
  }
  post'/reactions', to: 'reactions#user_reaction', as: 'user_reaction'
  get '/my_reactions', to: 'reactions#publication_with_reactions', as: 'my_reactions'

  get 'homes/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
   root "homes#index"
   get "/publications", to: "publications#index", as: "user_root" 
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
    before_action :authenticate_user!
  
    def user_reaction
        def user_reaction
            @user = current_user
            @publication = Publication.find(params[:publication_id])
            reaction = Reaction.find_by(user_id: @user.id, publication_id: @publication.id)
                if reaction
                    return flash.now[:alert] = 'You already reacted to this product'
                else
                    @new_reaction = Reaction.new(user_id: @user.id, publication_id: @publication.id, kind: params[:kind])
                        respond_to do |format|
                                        if @new_reaction.save!
                                            format.html { redirect_to publication_path(@publication), notice: "#{current_user.email} has stated that it #{@new_reaction.kind}
                                        the product" }
                                        else
                                            format.html { redirect_to publication_path(@publication), status: :unprocessable_entity }
                                        end
                                    end
                end
        end
    end
  
        def publication_with_reactions
            @reactions = current_user.reactions
            publication_ids = @reactions.map(&:publication_id)
            @publications = Publication.where(id: publication_ids)
        end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_counters.html.erb
<div class="container mt-4">
    <ul class="list-group">
      <% Reaction.kinds.each do |kind| %>
        <li class="list-group-item">
          <%= @publication.count_with_kind(kind) %>
        </li>
      <% end %>
    </ul>
  </div>
  

app/views/reactions/_options.html.erb
<div class="container mt-4">
    <div class="btn-group" role="group" aria-label="Reactions">
      <% Reaction.kinds.each do |kind| %>
        <%= button_to "#{kind}", user_reaction_path(publication_id: @publication.id, kind: kind), method: :post, class: "btn btn-primary mb-2 mr-2" %>
      <% end %>
    </div>
  </div>
  

app/views/reactions/publication_with_reactions.html.erb
<div class="container mt-4">
    <h1>Publicaciones</h1>
    <ul class="list-group">
      <% @publications.each do |publication| %>
        <li class="list-group-item">
          <%= publication.title %> -
          <%= publication.find_kind_user_relation(current_user) %>
          <p>
            <%= link_to "Show this publication", publication, class: "btn btn-link" %>
          </p>
        </li>
      <% end %>
    </ul>
  </div>
  